"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { CheckCircle2, Clock3, ShieldAlert, Timer } from "lucide-react";
import { getAdminVerifications } from "../../../services/auth.service";

export default function AdminVerificationsPage() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { getAdminVerifications().then((r) => setItems(r.data?.data?.verifications || [])).catch(() => setError("Unable to load the verification pipeline.")).finally(() => setLoading(false)); }, []);
  const inProgress = items.filter(({ property }) => property.verificationStatus !== "VERIFIED"); const completed = items.filter(({ property }) => property.verificationStatus === "VERIFIED"); const flagged = items.filter(({ property }) => property.verificationStatus === "ACTION_REQUIRED");
  const cards = [["Pending", inProgress.length, Clock3, "text-[#b96b00] bg-[#fff3d8]"], ["In progress", items.filter(({ verification }) => verification?.overallStatus === "IN_PROGRESS").length, Timer, "text-[#0759d6] bg-[#e8f0ff]"], ["Completed", completed.length, CheckCircle2, "text-[#16824d] bg-[#e5f8ef]"], ["Flagged", flagged.length, ShieldAlert, "text-[#c1372d] bg-[#fff0ee]"]];
  return <main className="px-5 py-8 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0759d6]">Verification operations</p><h1 className="mt-2 text-3xl font-bold tracking-[-.035em] text-[#182230]">Verification pipeline</h1><p className="mt-2 text-[15px] text-[#667085]">Live due diligence, inspection, and legal-clearance data.</p>{error && <p className="mt-5 text-sm text-[#b42318]">{error}</p>}<section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, tone]) => <article key={label} className="rounded-2xl border border-[#e4e8ef] bg-white p-5 shadow-[0_4px_18px_rgba(16,24,40,.035)]"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#758093]">{label}</p><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${tone}`}><Icon size={19} /></span></div><p className="mt-6 text-3xl font-bold text-[#273142]">{loading ? "—" : value}</p></article>)}</section><section className="mt-6 overflow-hidden rounded-2xl border border-[#e4e8ef] bg-white shadow-[0_4px_18px_rgba(16,24,40,.035)]"><div className="border-b border-[#e7ebf1] px-6 py-5"><h2 className="font-bold text-[#273142]">Active pipeline</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#fafbfc] text-[11px] uppercase tracking-[.09em] text-[#758093]"><tr><th className="px-6 py-4">Property</th><th className="px-4 py-4">Agent</th><th className="px-4 py-4">Stage</th><th className="px-4 py-4">Status</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{loading ? <tr><td colSpan="5" className="px-6 py-12 text-center text-sm text-[#758093]">Loading pipeline…</td></tr> : items.length ? items.map(({ property, verification }) => <tr key={property._id} className="hover:bg-[#fafcff]"><td className="px-6 py-4"><p className="font-semibold text-[#273142]">{property.title}</p><p className="mt-1 text-xs text-[#8791a1]">{property.locationText}</p></td><td className="px-4 py-4 text-sm text-[#667085]">{verification?.assignedAgent?.fullName || "Unassigned"}</td><td className="px-4 py-4 text-sm text-[#455063]">{property.statusLabel}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${property.verificationStatus === "ACTION_REQUIRED" ? "bg-[#fff0ee] text-[#c1372d]" : "bg-[#e8f0ff] text-[#0759d6]"}`}>{property.verificationStatus.replaceAll("_", " ")}</span></td><td className="px-6 py-4 text-right"><Link href={`/admin/properties/${property._id}`} className="text-sm font-semibold text-[#0759d6]">Review</Link></td></tr>) : <tr><td colSpan="5" className="px-6 py-12 text-center text-sm text-[#758093]">No active verifications.</td></tr>}</tbody></table></div></section></div></main>;
}
