export const lawyers = [
  { id: "priya-sharma", name: "Priya Sharma", initials: "PS", city: "Bengaluru", experience: 14, rating: 4.9, reviews: 128, fee: 1800, response: "Usually responds in 1 hour", languages: ["English", "Hindi", "Kannada"], specialties: ["Title & ownership", "Sale agreements", "Due diligence"], about: "Property-law specialist helping buyers and sellers complete clear, well-documented transactions.", image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=600&q=80", availability: "Available this week" },
  { id: "arjun-mehta", name: "Arjun Mehta", initials: "AM", city: "Mumbai", experience: 11, rating: 4.8, reviews: 96, fee: 2200, response: "Usually responds in 2 hours", languages: ["English", "Hindi", "Marathi"], specialties: ["Commercial property", "Lease agreements", "RERA matters"], about: "Advises on commercial purchases, leases, redevelopment, and regulatory property matters.", image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80", availability: "Available tomorrow" },
  { id: "neha-iyer", name: "Neha Iyer", initials: "NI", city: "Chennai", experience: 9, rating: 4.9, reviews: 74, fee: 1600, response: "Usually responds in 30 minutes", languages: ["English", "Tamil", "Hindi"], specialties: ["Home loans", "Property disputes", "Documentation"], about: "Focused on residential purchases, mortgage documentation, and resolving property documentation gaps.", image: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&w=600&q=80", availability: "Available today" },
  { id: "kabir-singh", name: "Kabir Singh", initials: "KS", city: "Delhi NCR", experience: 17, rating: 4.7, reviews: 163, fee: 2500, response: "Usually responds same day", languages: ["English", "Hindi", "Punjabi"], specialties: ["Land records", "Inheritance", "Litigation"], about: "Senior counsel for complex title records, inherited property, and property dispute strategy.", image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=600&q=80", availability: "Limited availability" },
  { id: "aisha-khan", name: "Aisha Khan", initials: "AK", city: "Hyderabad", experience: 8, rating: 4.8, reviews: 59, fee: 1500, response: "Usually responds in 1 hour", languages: ["English", "Hindi", "Telugu"], specialties: ["Property registration", "Rental agreements", "NRI property"], about: "Helps families and NRI clients with registration, rentals, and remote property transactions.", image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80", availability: "Available this week" },
  { id: "rohan-desai", name: "Rohan Desai", initials: "RD", city: "Pune", experience: 12, rating: 4.6, reviews: 87, fee: 1900, response: "Usually responds in 3 hours", languages: ["English", "Hindi", "Marathi"], specialties: ["Society transfer", "Builder disputes", "Due diligence"], about: "Works on society transfers, builder documentation, and practical buyer-side due diligence.", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80", availability: "Available this week" },
];

export const specialtyOptions = ["All specialties", ...new Set(lawyers.flatMap((lawyer) => lawyer.specialties))];

export const getLawyer = (id) => lawyers.find((lawyer) => lawyer.id === id);
